project:
  type: book

book:
  title: "Thesis"
  author: "Ivan Dubrovin"
  date: today
  chapters:
    - index.qmd
    - chapters/01_introduction.qmd
    - chapters/02_literature_review.qmd
    - chapters/03_materials_and_methods.qmd
    - chapters/04_results.qmd
    - chapters/05_conclusion.qmd
    - chapters/99_references.qmd
  cover-image: cover.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



