project:
  type: book

book:
  title: "A deep learning framework for mixed dense forests parameter estimation at individual tree scale"
  output-file: "my-book"
  author: "Ivan Dubrovin"
  date: today
  abstract: |
    This is an abstract.
    It is relatively long.
    It summarizes everything nicely.
  chapters:
    - index.qmd
    - chapters/01_introduction.qmd
    - chapters/02_literature_review.qmd
    - chapters/03_materials_and_methods.qmd
    - chapters/04_results.qmd
    - chapters/05_conclusion.qmd
    - chapters/99_references.qmd
  cover-image: cover.png
  downloads: [pdf]
  repo-url: https://github.com/iod-ine/thesis
  repo-actions: [edit, issue, source]
  sidebar:
    search: true
    title: "Tree-scale parameter estimation with deep learning"

bibliography: references.bib

execute:
  include: false

lightbox: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    output-file: "my-book"
