project:
  type: book

book:
  title: "Thesis"
  author: "Norah Jones"
  date: "2/8/2024"
  chapters:
    - index.qmd
    - chapters/01_introduction.qmd
    - chapters/02_related_workds.qmd
    - chapters/03_materials_and_methods.qmd
    - chapters/04_results.qmd
    - chapters/05_conclusion.qmd
    - chapters/99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



