[tool.poetry]
name = "thesis"
version = "0.1.0"
description = ""
authors = ["Ivan Dubrovin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
