## Lysva field inventory dataset

The main original dataset used in the study is the Lysva field inventory dataset, named by the closest town to its location.
It is located in Perm Krai, Russia, 86 kilometers to the east of Perm.
It consists of a field inventory of 3600 trees across 10 rectangular ground plots 100 meters in lengths and 50 meters in width fully covered by a UAV LiDAR and RGB orthophoto surveys.
Every tree is represented as a point in UTM 40N coordinate reference system (EPSG:32640),


@tbl-inventory-example shows a sample of entries from the field inventory table.

{{< embed 03a_lysva_dataset.ipynb#tbl-inventory-example >}}

@fig-example-3d-point-cloud is a 3D visualization of the point cloud over plot number 10.

{{< embed 03a_lysva_dataset.ipynb#fig-example-3d-point-cloud >}}

{{< embed 03a_lysva_dataset.ipynb#fig-example-ortho >}}

@fig-lysva-species-distribution show the distribution of species in the Lysva dataset.

{{< embed 03a_lysva_dataset.ipynb#fig-lysva-species-distribution >}}

@tbl-lysva-plot-stats shows stats for plots in the Lysva dataset.

{{< embed 03a_lysva_dataset.ipynb#tbl-lysva-plot-stats >}}

### On using intensity-based features {#sec-intensity-based-features}

Even though some sources report intensity-based features as some of the most important ones [@shiImportantLiDARMetrics2018], the features seem to me unreliable in the context of forestry because of the physics of light reflection.
There are simply too many factors that affect the amplitude of the reflected signal, which might be useful when imaging stable targets such as urban environments but become completely unpredictable on highly unstable targets such as trees: they move in the wind in the time span of a single survey, they grow in the time span between repeated surveys, the leaves and branches are angled in every possible way.
Moreover, the quality of the recorded intensities highly depends on the used sensor.
As an example, @fig-intensity-with-example shows the distribution of intensity values for every point in the Lysva dataset, and shows plot number 10 in 3D with points colored by their recorded intensity.
The distribution of intensities seems like an artifact of faulty quantization (the fact that the maximum overall value is 63 makes me suspect it is stored by the hardware using a 6-bit unsigned integer, probably an ad hoc optimization by the sensor vendor).
With this distribution in mind, it is not surprising that coloring points by their intensity values results in images that look like noise, and there is no signal to be exploited for predictive modeling.

{{< embed 03a_lysva_dataset.ipynb#fig-intensity-with-example >}}

Some sensors do provide more consistent values.
However, relying on intensity-based features limits the applicability of developed models and methods, as any such model would surely fail on data like this.
